name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  nargo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install nargo
        run: |
          curl -L https://raw.githubusercontent.com/noir-lang/noirup/main/install | bash
          export PATH="$PATH:/home/runner/.nargo/bin:.nargo/bin/nargo"
          noirup -v 0.16.0-aztec.1

      - name: Run nargo check token
        run: |
          export PATH="$PATH:/home/runner/.nargo/bin:.nargo/bin/nargo"
          cd src/contracts/token
          nargo check
          nargo test

      - name: Run nargo check webauthn
        run: |
          export PATH="$PATH:/home/runner/.nargo/bin:.nargo/bin/nargo"
          cd src/contracts/webauthn
          nargo check
          nargo test
